### ISSUE TITLE
Cannot install typings when using bower

### ISSUE THREAD

**Issue by antglenn** [highcharts/highcharts-declarations-beta#2]
Hi,

Having previously been using the `sophiebremer/highcharts-declarations-alpha` declarations, since the move to the `highcharts/highcharts-declarations-beta` and deletion of the old repository we can no longer install the declarations file while using bower to install highcharts v6.

This was possible with the previous set of declarations, and highcharts is available via bower. Please can you make the beta declarations available when using bower?

Many thanks,

**Comment by bre1470** [comment]
Hello!

Thank you for the feedback. We will look into the issue and hopefully solve the problem with the next beta version.

Best regards,

**Comment by bre1470** [comment]
This problem can not be solved with the installation process of the Beta phase. A possible workaround is to install `highcharts` and `highcharts-declarations-beta` via npm and use the modified `node_modules/highcharts` as the installation source for bower.

**Comment by bre1470** [comment]
Also please note that bower is itself deprecated.
