### ISSUE TITLE
Typing for xAxis.labels.formatter

### ISSUE THREAD

**Issue by jonfreedman** [highcharts/highcharts-declarations-beta#20]
As per https://api.highcharts.com/highcharts/xAxis.labels.formatter the formatter function makes use of a differently scoped `this` variable.

Not sure if there is a fix for this other than to change highcharts itself to introduce a function parameter?

**Comment by bre1470** [comment]
Thank you for the feedback. This can probably be fixed by explicitly setting `this` as the first parameter. I will look into it.

**Comment by jonfreedman** [comment]
Just to close this out the typescript code looks like this (where lookup is an [immutable map](https://facebook.github.io/immutable-js/docs/#/Map/get))

    labels: {
      formatter(this: AxisLabelsFormatterContextObject) {
        return lookup.get(this.value, '?');
      }
    }
