### ISSUE TITLE
ExportingButtonsContextButtonOptions needs expansion to include menuItems defined as objects

### ISSUE THREAD

**Issue by cthrax** [highcharts/highcharts-declarations-beta#26]
Currently the menuItems type is "Array<string>", but it can also be "Array<menuItemDefinitions>" according to documentation (and my current use case). [Docs](https://api.highcharts.com/highcharts/exporting.buttons.contextButton.menuItems )

The workaround right now is to use menuItemDefinitions and refer to the label instead of doing it inline, but it'd be nice to extend this out.

**Comment by bre1470** [comment]
Thank you for the feedback again. I have to get in touch with the product owner, whether this is done by intention or not.

**Comment by bre1470** [comment]
Hi! I have new information about this issue. The support of `Array<objects>` is for backwards compatibility and not recommend. Therefor we will not integrate it into the TypeScript declarations and fix the API documentation. It should actually not be listed there as a possible type.

**Comment by cthrax** [comment]
@bre1470 Thanks for the quick response, does that mean I should be changing my current use of the API to conform? It's pretty convenient to inline those definitions so I don't have to tie strings together, but I understand if that's changing.

**Comment by bre1470** [comment]
Yes, we recommend that you change it, even though Highcharts v7 will still support the old construct.
