### ISSUE TITLE
Incorrect type signatures

### ISSUE THREAD

**Issue by gbenthomas** [highcharts/highcharts-declarations-beta#28]
- `Axis.update`, `Tooltip.update`, `SubtitleObject.update`, and `TitleObject.update` are missing the `redraw` parameter
- `options` parameter in `addEvent` should be optional and `order` parameter should be removed
- `e: Event` parameter should be optional in `Chart.reflow`

**Comment by bre1470** [comment]
Thank you for the issue report. Please add further issue reports in the future to https://github.com/highcharts/highcharts. The TypeScript declarations are now part of the Highcharts repository itself.

**Comment by SovietFrontier** [comment]
Have they issued out TypeScript declarations for `v7` and above or did they get `v6` too?

**Comment by bre1470** [comment]
Both will get the fix. The update for v7 contained some failures and we focus now first on improving the test system, so that typos get reliable catched before release. I will start tomorrow with the review of the update for v6 and if everything is fine, the beta gets released.

**Comment by bre1470** [comment]
The beta declarations for Highcharts v6 are now available.
