### ISSUE TITLE
showLoading optional parameter

### ISSUE THREAD

**Issue by Nosfistis** [highcharts/highcharts-declarations-beta#31]
`showLoading()` parameter is optional, yet it is required in the typings.

**Comment by SovietFrontier** [comment]
Might be able to fix that real quick..

**Comment by bre1470** [comment]
Thank you for reporting the issue. Do you need a fix for v6.2 or v7.x?

**Comment by Miced** [comment]
I am still in the process of migrating from 6.1 to 7, so I have no preference.

**Comment by SovietFrontier** [comment]
@bre1470 thanks for making these fixes so quick. You do a good job on this repo!
