### ISSUE TITLE
Highcharts param fn has wrong type in map function 

### ISSUE THREAD

**Issue by LoganDupont** [highcharts/highcharts-declarations-beta#4]
I guess there is a mistake in the map function as the return type of the param fn is now set to type void.
![image](https://user-images.githubusercontent.com/6780720/48059254-e8c11480-e1b8-11e8-9e83-491a35a63b1a.png)

Because without types i was able to return a value and now it's complaining
```
this.chartOptions = {
      colors: Highcharts.map(this.colors, function(color) {
        return {
          radialGradient: {
            cx: 0.5,
            cy: 0.8,
            r: 0.9
          },
          stops: [
            [0, color],
            [1, color.brighten(-0.35).get('rgb')] // darken
          ]
        };
      }),
};
```

**Comment by LoganDupont** [comment]
I created a PR for it (#5)

**Comment by bre1470** [comment]
It will be fixed with this pull request: https://github.com/highcharts/highcharts/pull/9297/files

**Comment by bre1470** [comment]
Fix is no incorporated into next beta: https://github.com/highcharts/highcharts-declarations-beta/pull/3
