### ISSUE TITLE
Axis needs to support both a single object and array of objects

### ISSUE THREAD

**Issue by muperi** [highcharts/highcharts-declarations-beta#6]
The API supports both object as well as array of objects.

    xAxis?: XAxisOptions | XAxisOptions[];
    yAxis?: YAxisOptions | YAxisOptions[];

**Comment by bre1470** [comment]
Thank you for pointing this out. I will look into it. The generator is probably missing something.

**Comment by bre1470** [comment]
Fix is no incorporated into next beta: https://github.com/highcharts/highcharts-declarations-beta/pull/3
