### ISSUE TITLE
ChartEventsOptions Selection is missing the parameter

### ISSUE THREAD

**Issue by muperi** [highcharts/highcharts-declarations-beta#7]
ChartEventsOptions - selection is missing the SelectEventObject parameter and return type of boolean

selection?: (e: SelectEventObject) => boolean;

**Comment by bre1470** [comment]
Thank you for the feedback. This will be fixed. I am unsure about the return type. The API documentation says, that you have to use `event.preventDefault()` to prevent zoom.

**Comment by bre1470** [comment]
It will be fixed with this pull request: https://github.com/highcharts/highcharts/pull/9305

**Comment by bre1470** [comment]
Fix is no incorporated into next beta: https://github.com/highcharts/highcharts-declarations-beta/pull/3
