### ISSUE TITLE
Cannot find module 'highcharts' after installing, Type is not assignable to type issues

### ISSUE THREAD

**Issue by itsnotatbug** [highcharts/highcharts-declarations-beta#8]
I am using VSCode. So I uninstalled `@types/highcharts` and replaced it with this. No errors for the most part, except the fact that for whatever reason, I am having import issues. `import * as Highcharts from 'highcharts';` is giving me: 

> Cannot find module 'highcharts'

I am having no luck trying to fix this. I have cleared cache, updated to `Highcharts 6.2` then installed the `highcharts-declarations-beta` again, tried to use `import { Highcharts } from 'highcharts'` and still no luck.

What am I doing wrong?

**Comment by bre1470** [comment]
The setting of `module` influences the way TypeScript searches for modules (`moduleResolution`). You should set `moduleResolution` always to `node`.

**Comment by bre1470** [comment]
You also need to install highcharts first. So first
```sh
npm i highcharts
```
... and afterwards ...
```sh
npm i https://github.com/highcharts/highcharts-declarations-beta.git
```

**Comment by bre1470** [comment]
Yes, that is caused by the more detailed options. It now distinguishes between the different series types by interfaces. Use
```TypeScript
	series: [
		{
			id: 'myNameID',
			name: 'myName',
			data: myData,
			cursor: 'pointer',
			type: 'column',
			colors: ['red', 'blue']
		} as Highcharts.SeriesColumnOptions

**Comment by SovietFrontier** [comment]
**I appreciate all the help!** Sorry to keep bugging you here, but eventually I won't be the only one having questions.

I see! I have a dual series, with a line. Added the `.SeriesLineOptions` and my errors disappeared.
But when I compiled, I still got the same issue with `data`, `cursor`, and `name`.
> TS2322: Type '{ name: string; data: any[]; cursor: string; }' is not assignable to type 'SeriesOptions'.
>   Object literal may only specify known properties, and 'data' does not exist in type 'SeriesOptions'.

Here is my `tsconfig.json`:
```
{
	"compilerOptions": {
		"declaration": true,
		"experimentalDecorators": true,
		"noImplicitAny": true,
		"lib": [ "es2015", "dom" ],
		"module": "es6",
		"moduleResolution": "node",
		// "allowJs": true,
		"outDir": "./dist",
		"sourceMap": true,
		"strict": false,
		"target": "es5",
		"typeRoots": [
			"./node_modules/@types/"
		]
	},
	"exclude": [
		"node_modules/*",
		"test/*",
		"src/**/*.spec.ts",
		"dist/*"
	]
}
```
Here is my `webpack.config.js`:
```
const path = require('path');
var HtmlWebpackInlineSourcePlugin = require('html-webpack-inline-source-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
	entry: './src/myFileName/myFileName.ts',
	output: {
		filename: 'myFileName.js',
		path: path.resolve(__dirname, 'dist/myFileName')
	},
	mode: 'production',
	module: {
		rules: [
			{
				test: /\.ts?$/,
				use: 'ts-loader',
				exclude: /node_modules/
			},
			{
				test: /\.css$/,
				use: ['style-loader', 'css-loader']
			}
		]
	},
	resolve: {
		extensions: ['.tsx', '.ts', '.js']
	},
	plugins: [
		new HtmlWebpackPlugin({
			inlineSource: '.(js|css)$',
			filename: 'myFileName.html',
			// title: 'titleHere',
			template: 'src/myFileName/myFileNameTemplate.html'
		}),
		new HtmlWebpackInlineSourcePlugin(),
	]
};
```

**NOTE~** I answered my own question by digging in. Once webpacking, it actually goes into all of my source and finds the errors, not just the specific report or `.ts` file I was working with/compiling at the time. Pretty neat. I will leave all of this here for people who have questions on set up. My set up **webpacks `.ts` into a `.js` file and _inlines_ the javascript into one `.html` document**.

**Comment by SovietFrontier** [comment]
Also how do you read these? 
https://raw.githubusercontent.com/highcharts/highcharts-declarations-beta/master/highcharts.d.ts
I want to learn what these mean so I can try and figure it out myself. Googling `how to read .d.ts`  isn't helping much.

**Comment by bre1470** [comment]
Great, that you could solve the problem with webpack configuration.

Regarding your second question: The declaration files are not intended for developers. They are used by the TypeScript compiler and TypeScript-capable editors to point developers to problems and to suggest functions and options on the fly in the editor. If you like to get an overview outside your development platform, our API documentation is the best choice: https://api.highcharts.com/
In fact the API documentation and the TypeScript declarations are generated out of the same sources.

**Comment by SovietFrontier** [comment]
> If you like to get an overview outside your development platform, our API documentation is the best choice: https://api.highcharts.com/
> In fact the API documentation and the TypeScript declarations are generated out of the same sources.

That is what I use for the most part. I wasn't able to find anything about interfaces there but it dawned on me that is beta. I was just having a hard time piecing those two together. It was just a lack of understanding how that all worked. Everything is fine and dandy for me now though. Appreciate the comment you made in the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/22893) repository which led me here!

Thanks a bunch. Hope this helps other peeps too.

**Comment by bre1470** [comment]
Sticky series types are now working:
```
	series: [
		{
			id: 'myNameID',
			name: 'myName',
			data: myData,
			cursor: 'pointer',
			type: 'column',
			colors: ['red', 'blue']
		}
	]
```

**Comment by itsnotatbug** [comment]
@bre1470 I am getting errors with the series types. You mentioned previously, that they will not need to be cast anymore, but I updated to `highcharts-declarations-beta@0.9.0` and I am getting this error, from the following code:

```
series: [
   {
	type: 'column',
	id: 'prsColumn',
	name: 'PRS Sales',
	legendColor: '',
	data: myData,
	cursor: 'pointer'
   }
]
```

> TS2322: Type 'string' is not assignable to type '"ad" | "area" | "arearange" | "areaspline" | "areasplinerange" | "atr" | "bar" | "bb" | "bellcurve" | "boxplot" | "bubble" | "bullet" | "candlestick" | "cci" | "cmf" | "column" | ... 49 more ... | "zigzag"'.


The error is on the `type:` element. When I add the `<Highcharts.SeriesColumnOptions>` before the elements, the error goes away.

***EDIT***: Well, apparently it's just not finding it properly so I **have** to cast it, according to [parts of the API.](https://www.highcharts.com/docs/advanced-chart-features/typescript) I am seeing some other issues pop up between my previous `v0.3.2` of the beta declarations, and the `v0.9.0` though, so hopefully I can fix em all without much issue.

**Comment by bre1470** [comment]
Thank you for the feedback!

I believe, the Array is somehow the problem. If you cast it like this, does it work for you?
```
series: <Array<Highcharts.SeriesOptionsType>>[
    {
        type: 'column',
        id: 'prsColumn',
        name: 'PRS Sales',
        legendColor: '',
        data: myData,
        cursor: 'pointer'
    }
]
```

**Comment by bre1470** [comment]
Hi again. It would be nice, if you could tell me the TypeScript version, in which you have this problem.

**Comment by bre1470** [comment]
Okay, I found your problem: `legendColor` is not a valid property for `SeriesColumnOptions`. Without this property there is no complain by TypeScript for me. Where did you found legendColor? Do you try to add custom properties to your series?

**Comment by itsnotatbug** [comment]
I found the `legendColor` from a `StackOverflow` [question.](https://stackoverflow.com/questions/36112858/change-the-color-of-legend-symbol-highchart) It never seemed to work for me, but it never threw any errors.  I have reverted back to `v0.3.0` because I was having issues figuring out how to get the tooltip to work again because the `formatter` disappeared.

```
tooltip: {
formatter: function () {
	if (this.series.options === 'someOtherSeries') {
		return false;
	} else {
		return (
			`<div class='toolTipHeader'></div>`
			+ `<table>`
			+ `<tbody>`
			+ `<tr>`
			+ `<td><div class='toolTipCell toolTipCaption'>small tooltip:</div></td>`
                        + `</tr>
                        + `</tbody>
                        + `</table>
		);
	}
},
useHTML: true
},
```

I used this callback to show my hovers with `v0.3.0`.
